### ISSUE TITLE
Implicit routing in TAXII 1.1 Inboxes

### ISSUE THREAD

**Issue by margaretbloom** [eclecticiq/OpenTAXII#124]
What's the point of the `destination_collection_required` property of an Inbox service?

If I understand its use correctly, it forces [`validate_destination_collection_names`](https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/taxii/services/inbox.py#L58) to return an empy list due to [these lines](https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/taxii/services/inbox.py#L81).  
This in turn makes the [`correct_binding_collections` list empty](https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/taxii/services/handlers/inbox_message_handlers.py#L44) leading to OpenTAXII ignoring all the content.

Is `destination_collection_required` used to activate the Implicit Routing of a TAXII 1.1 Inbox? If not what's the point of setting it to `False`?
Wouldn't be better to return the destination collections in case of `destination_collection_required` set to `False`?

**Comment by traut** [comment]
TAXII 1.x spec allows clients to push data into TAXII Inbox without defining destination collection. That might be not desirable, that's why `destination_collection_required` setting was added.

Indeed, looks like when `name_list` is empty and `destination_collection_required` is set to `False`, `validate_destination_collection_names` will return an empty list, forcing `correct_binding_collections` list [to be empty](https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/taxii/services/handlers/inbox_message_handlers.py#L44). 

Nicely spotted, thank you. This is a bug.

**Comment by erwin-eiq** [comment]
Fixed. Sorry for the rather massive delay @margaretbloom but thanks for the bugreport!
