### ISSUE TITLE
Creating a custom webservice

### ISSUE THREAD

**Issue by thanujarc** [eclecticiq/OpenTAXII#166]
Hi, 

I'm just starting to use opentaxii and I'm a bit confused about where and how to create a custom web service. The environment is quite different to Apache or similar web services. 
Can someone please assist me in implementing a simple web service?. Specifically, where should I place my python files for the new web service? What is the structure and format of the files I need to create in order to create a new custom web service using opentaxii?
My development environment is CentOS 7.

Thanks.

**Comment by arcsector** [comment]
@thanujarc this is very different from Apache httpd because Apache httpd is a web server, whereas this is a wsgi web application. Where httpd only provides the front end, this provides front and back end.

You should readup on the core softwares involved in this before you use this project, namely flask and gunicorn. They will give you a better sense of what is going on and what you need to do.

For instructions after that, check the docs.

**Comment by traut** [comment]
@thanujarc this might help - https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-ubuntu-14-04

**Comment by arcsector** [comment]
@thanujarc did this work for you?
