### ISSUE TITLE
services.yml and collections.yml missing from example directory

### ISSUE THREAD

**Issue by hidde-jan** [eclecticiq/OpenTAXII#89]
Links in https://opentaxii.readthedocs.io/en/stable/configuration.html#creating-services-and-collections to these two files are also broken, which makes completing the short getting-started-guide/tutorial rather difficult.

**Comment by traut** [comment]
@hidde-jan thanks for pointing that out! the links in the docs should've been pinpointed to a specific revision. Since these are "stable" docs, I can not fix it in master, only in the next release

Here are the files from latest "stable" tag: [collections.yml](https://github.com/EclecticIQ/OpenTAXII/blob/3c4309f364ac2b0e04ba14f41cb3ce7b6f274667/examples/collections.yml) and [services.yml](https://github.com/EclecticIQ/OpenTAXII/blob/3c4309f364ac2b0e04ba14f41cb3ce7b6f274667/examples/services.yml)

**Comment by hidde-jan** [comment]
Great, thanks!

Op 25 okt. 2017 1:36 p.m. schreef "Sergey Polzunov" <
notifications@github.com>:

**Comment by traut** [comment]
documentation is updated in the new [release 0.1.10](https://github.com/eclecticiq/OpenTAXII/releases/tag/0.1.10).
